set(SYNTAX_GEN_SYNTAX_CATEGORIES "Decl;Stmt;Expr;Type;Pattern;Generic;Attribute")
set(SYNTAX_GEN_OTHER_CATEGORIES "SyntaxFactory;SyntaxRewriter")
set(SYNTAX_GEN_CATEGORIES ${SYNTAX_GEN_SYNTAX_CATEGORIES} ${SYNTAX_GEN_OTHER_CATEGORIES})
