#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/Signals.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Main.h"
#include "llvm/TableGen/Record.h"

using namespace llvm;

enum class ActionType {
  None,
  GenImplementation,
  GenInterface,
};

enum class Category {
  Unknown,
  Decl,
  Expr,
  Stmt,
  Type,
  Pattern,
  Generic,
  Attribute,
  SyntaxFactory,
  SyntaxRewriter,
};

enum class TargetLanguage {
  CPlusPlus,
};

RecordKeeper *AllRecords;
SmallSet<const Record *, 8> SyntaxCategories;

namespace options {
static cl::opt<ActionType> Action(
  cl::desc("Action to perform: "),
  cl::init(ActionType::None),
  cl::values(
    clEnumValN(ActionType::GenImplementation, "implementation",
      "Generate the implementation for the given syntax category"),
    clEnumValN(ActionType::GenInterface, "interface",
      "Generate the interface for the given syntax category")
    )
);
static cl::opt<TargetLanguage> Language(
  "language",
  cl::desc("Target language to emit: "),
  cl::init(TargetLanguage::CPlusPlus),
  cl::values(
    clEnumValN(TargetLanguage::CPlusPlus, "c++",
      "Generate the interface or implementation in C++")
  )
);
static cl::opt<std::string> Category(
  "category",
  cl::desc("Category to emit"));

} // end options namespace

#pragma mark - Helpers

static void printAutogenReminder(raw_ostream &OS) {
  OS << "/// This file autogenerated by swift-syntax-tblgen - DO NOT EDIT!\n";
  OS << "\n";
}

/// Returns true if the record type is a subclass of Syntax.
/// Used to filter out values in a record that tablegen automatically inserts, like NAME,
/// or auxiliary fields that we have added, like IsRequired.
static bool is(const RecTy *Ty, StringRef TypeName) {
  if (auto RecordTy = dyn_cast<RecordRecTy>(Ty)) {
    if (RecordTy->getAsString() == TypeName || RecordTy->getRecord()->isSubClassOf(AllRecords->getClass(TypeName))) {
      return RecordTy;
    }
  }
  return nullptr;
}

static bool isToken(const RecTy *Ty) {
  return is(Ty, "Token");
}

static bool isIdentifier(const RecTy *Ty) {
  return is(Ty, "Identifier");
}

static bool isLayout(const RecTy *Ty) {
  return is(Ty, "Layout");
}

static const Record *getLayoutNodeRecord(const Record *Rec) {
  auto NodeField = Rec->getValue("Node");
  auto NodeValue = cast<DefInit>(NodeField->getValue());
  return NodeValue->getDef();
}

static const Record *getLayoutNodeRecord(const RecordVal Child) {
  assert(isLayout(Child.getType()));
  auto RHS = cast<DefInit>(Child.getValue());
  auto NodeDef = RHS->getDef();
  return getLayoutNodeRecord(NodeDef);
}

static const Record &
getSyntaxCategory(const Record *Def) {
  for (const auto Super : Def->getSuperClasses()) {
    if (SyntaxCategories.count(Super.first)) {
      return *Super.first;
    }
  }
  llvm_unreachable("Record didn't have a syntax category??");
}

bool canBeAnyOfSyntaxCategory(const RecordVal Child) {
  auto Node = getLayoutNodeRecord(Child);
  return Node->getName().startswith("Any");
}

static const RecordRecTy *getLayoutNodeType(const RecordVal Child) {
  assert(isLayout(Child.getType()));
  auto RHS = cast<DefInit>(Child.getValue());
  auto NodeDef = RHS->getDef();
  auto NodeField = NodeDef->getValue("Node");
  auto NodeValue = cast<DefInit>(NodeField->getValue());
  auto NodeType = NodeValue->getType();
  if (isToken(NodeType)) {
    NodeType = AllRecords->getClass("Token")->getDefInit()->getType();
  }
  return cast<RecordRecTy>(NodeType);
}

static StringRef getTokenSpelling(const RecordVal Value) {
  assert(isLayout(Value.getType()));
  auto TokenRec = getLayoutNodeRecord(Value);
  for (const auto Field : TokenRec->getValues()) {
    if (Field.getName() == "Spelling") {
      return Field.getValue()->getAsUnquotedString();
    }
  }
  return StringRef();
}

static StringRef stripSyntaxSuffix(StringRef TypeName) {
  auto Pos = TypeName.rfind("Syntax");
  if (Pos == StringRef::npos) {
    return TypeName;
  }
  return TypeName.slice(0, Pos);
}

static std::string getMissingSyntaxKind(const RecordVal Child) {
  // TODO
  return "Missing";
}

static Category getCategory() {
  return llvm::StringSwitch<Category>(options::Category)
  .Case("Decl", Category::Decl)
  .Case("Expr", Category::Expr)
  .Case("Stmt", Category::Stmt)
  .Case("Type", Category::Type)
  .Case("Pattern", Category::Pattern)
  .Case("Generic", Category::Generic)
  .Case("Attribute", Category::Attribute)
  .Case("SyntaxFactory", Category::SyntaxFactory)
  .Case("SyntaxRewriter", Category::SyntaxRewriter)
  .Default(Category::Unknown);
}

static bool categoryIsInSyntaxHierarchy() {
  switch (getCategory()) {
  case Category::Decl:
  case Category::Expr:
  case Category::Pattern:
  case Category::Stmt:
  case Category::Type:
  case Category::Generic:
  case Category::Attribute:
    return true;
  default:
    return false;
  }
}

static bool shouldPrintDef(const Record &Rec) {
  auto Any = std::string { "Any" } + options::Category;
  if (Rec.getName() == Any) {
    return false;
  }
  if (Rec.getName().startswith("anonymous")) {
    return false;
  }
  if (Rec.getValueAsString("Category") != options::Category) {
    return false;
  }
  return true;
}

static std::vector<RecordVal> getChildrenOf(const Record &Node) {
  std::vector<RecordVal> Children;

  for (const auto Child : Node.getValues()) {
    if (!isLayout(Child.getType())) {
      continue;
    }
    Children.push_back(Child);
  }

  return Children;
}

static void printTokenAssertion(std::string VariableName,
                                const RecordVal Value,
                                raw_ostream &OS) {
  assert(isLayout(Value.getType()));
  auto Ty = getLayoutNodeType(Value);
  assert(isToken(Ty));
  auto TokenRec = getLayoutNodeRecord(Value);
  auto Kind = TokenRec->getValueAsString("Kind");
  if (canBeAnyOfSyntaxCategory(Value)) {
    OS << "  assert(" << VariableName << "->isToken());\n";
  } else {
    if (isIdentifier(Ty)) {
      OS << "  assert(" << VariableName << "->getTokenKind() == tok::" << Kind << ");\n";
    } else {
      OS << "  syntax_assert_token_is(" << VariableName << ", tok::" << Kind << ", \"" << getTokenSpelling(Value) << "\");\n";
    }
  }
}

static void printSyntaxAssertion(Twine ChildVariable,
                                 const RecordVal Child,
                                 raw_ostream &OS) {
  auto NodeType = getLayoutNodeType(Child);
  auto NodeTypeName = NodeType->getAsString();
  auto NodeKind = stripSyntaxSuffix(NodeTypeName);
  if (canBeAnyOfSyntaxCategory(Child)) {
    auto &Category = getSyntaxCategory(getLayoutNodeRecord(Child));
    OS << "  assert(" << ChildVariable << "->is" << Category.getName() << "());\n";
  } else {
    OS << "  assert(" << ChildVariable << "->getKind() == SyntaxKind::" << NodeKind << ");\n";
  }
}

static void printIncludesOfImplementation(raw_ostream &OS) {
  assert(options::Action == ActionType::GenImplementation);

  OS <<
  "#include \"swift/Syntax/RawSyntax.h\"\n"
  "#include \"swift/Syntax/SyntaxFactory.h\"\n"
  "#include \"swift/Syntax/" << options::Category;
  if (categoryIsInSyntaxHierarchy()) {
    OS << "Syntax";
  }
  OS << ".h\"\n";

  OS <<
  "using namespace swift;\n"
  "using namespace swift::syntax;\n"
  "using llvm::None;\n"
  "using llvm::Optional;\n\n";
}

static std::string getHeaderGuard() {
  SmallString<64> GuardScratch;
  raw_svector_ostream OS(GuardScratch);

  OS << "SWIFT_SYNTAX_" << StringRef(options::Category).upper();
  if (categoryIsInSyntaxHierarchy()) {
    OS << "SYNTAX";
  }
  OS << "_H";
  return OS.str();
}

struct HeaderGuard {
  raw_ostream &OS;
  HeaderGuard(raw_ostream &OS) : OS(OS) {
    OS << "#ifndef " << getHeaderGuard() << "\n";
    OS << "#define " << getHeaderGuard() << "\n\n";
  }

  ~HeaderGuard() {
    OS << "#endif // " << getHeaderGuard() << "\n";
  }
};

static void printIncludesOfInterface(raw_ostream &OS) {
  OS <<
  "#include \"swift/Syntax/References.h\"\n"
  "#include \"swift/Syntax/SyntaxData.h\"\n"
  "#include \"swift/Syntax/Syntax.h\"\n\n";
}

struct Namespaces {
  raw_ostream &OS;
  Namespaces(raw_ostream &OS) : OS(OS) {
    OS << "namespace swift {\n";
    OS << "namespace syntax {\n";
  }

  ~Namespaces() {
    OS << "} // end namespace syntax\n";
    OS << "} // end namespace swift\n";
  }
};

#pragma mark - Syntax

static bool printSyntaxInterface(const Record &Node, raw_ostream &OS) {
  auto ClassName = Node.getName();
  auto Kind = stripSyntaxSuffix(ClassName);
  auto SuperclassName = Node.getSuperClasses().back().first->getName();
  auto DataClassName = ClassName + "Data";

  OS << "class " << ClassName << " final : public Syntax {\n"
  "  friend struct SyntaxFactory;\n"
  "  friend class " << DataClassName << ";\n"
  "  friend class SyntaxData;\n"
  "\n"
  "  using DataType = " << DataClassName << ";\n"
  "\n";

  if (!getChildrenOf(Node).empty()) {
    OS << "  enum class Cursor : CursorIndex {\n";
    for (const auto Child : getChildrenOf(Node)) {
      OS << "    " << Child.getName() << ",\n";
    }
    OS << "  };\n";
  }

  OS <<
  "  " << ClassName << "(RC<SyntaxData> Root, const " << DataClassName << "* Data)\n"
  "    : " << SuperclassName << "(Root, Data) {}\n"
  "public:\n";
  for (const auto Child : getChildrenOf(Node)) {
    auto ChildType = cast<RecordRecTy>(Child.getType());
    auto ChildTypeName = getLayoutNodeType(Child)->getAsString();
    if (ChildType->getRecord() == AllRecords->getClass("Token")) {
      ChildTypeName = std::string("RC<") + ChildTypeName + ">";
    }

    OS << "  " << ChildTypeName << " get" << Child.getName() << "() const;\n";
    OS << "  " << ClassName << " with" << Child.getName() << "(" << ChildTypeName << " New" << Child.getName() << ") const;\n\n";
  }
  OS <<
  "  static bool classof(const Syntax *S) {\n"
  "    return S->getKind() == SyntaxKind::" << Kind << ";\n"
  "  }\n"
  "};\n\n";

  return false;
}

static bool printSyntaxDataInterface(const Record &Node, raw_ostream &OS) {
  auto ClassName = Node.getName();
  auto Kind = stripSyntaxSuffix(ClassName);
  auto DataClassName = ClassName + "Data";

  OS << "class " << DataClassName << " final : public SyntaxData {\n"
  "  friend class SyntaxData;\n"
  "  friend struct SyntaxFactory;\n"
  "\n" <<
  "  " << DataClassName << "(RC<RawSyntax> Raw, const SyntaxData *Parent = nullptr, CursorIndex IndexInParent = 0);\n"
  "\n"
  "  static RC<" << DataClassName << "> make(RC<RawSyntax> Raw, const SyntaxData *Parent = nullptr, CursorIndex IndexInParent = 0);\n"
  "  static RC<" << DataClassName << "> makeBlank();\n"
  "\n"
  "public:\n"
  "  static bool classof(const SyntaxData *SD) {\n"
  "    return SD->getKind() == SyntaxKind::" << Kind << ";\n"
  "  }\n"
  "};\n\n";
  return false;
}

static bool printSyntaxInterfaces(raw_ostream &OS) {
  HeaderGuard HG { OS };
  printIncludesOfInterface(OS);
  Namespaces NS { OS };
  const auto &Nodes = AllRecords->getDefs();
  for (const auto &Node : Nodes) {
    if (!shouldPrintDef(*Node.second)) {
      continue;
    }
    printSyntaxDataInterface(*Node.second, OS);
    printSyntaxInterface(*Node.second, OS);
  }

  return false;
}

static bool printSyntaxImplementation(const Record &Node, raw_ostream &OS) {
  auto ClassName = Node.getName();

  for (auto Child : getChildrenOf(Node)) {
    auto ChildName = Child.getName();
    auto ChildType = getLayoutNodeType(Child);
    auto ChildTypeName = ChildType->getAsString();
    auto OptionalChildTypeName = "llvm::Optional<" + ChildTypeName + ">";

    // Getter
    OS << OptionalChildTypeName << "\n" <<
    ClassName << "::get" << ChildName << "() const {\n"
    "  auto RawChild = getRaw()->getChild(Cursor::" << ChildName << ";\n"
    "  if (RawChild->isMissing()) {\n"
    "    return llvm::None;\n"
    "  }\n"
    "  auto *MyData = getUnsafeData<" << ClassName << ">();\n"
    "  auto &ChildPtr = *reinterpret_cast<std::atomic<uintptr_t>*>(\n"
    "    &MyData->Cached" << ChildName << ");\n"
    "  SyntaxData::realizeSyntaxNode<" << ChildTypeName << ">(ChildPtr, RawChild, MyData, cursorIndex(Cursor::" << ChildName << "));\n"
    "  return " << ClassName << "{ Root, MyData->Cached" << ChildName << ".get() };\n"
    "}\n\n";

    // Setter
    auto NewChildArg = "New" + ChildName;
    OS << ClassName << "\n" << ClassName << "::with" << ChildName << "(" << ChildTypeName << " " << NewChildArg << ") const {\n";
    if (isToken(ChildType)) {
      printTokenAssertion(NewChildArg.str(), Child, OS);
      OS << "  return Data->replaceChild<" << ClassName << ">(" << NewChildArg << ", " << "Cursor::" << ChildName << ");\n";
    } else {
      OS << "  return Data->replaceChild<" << ClassName << ">(" << NewChildArg << "->getRaw(), " << "Cursor::" << ChildName << ");\n";
    }
    OS << "}\n\n";
  }

  return false;
}

static bool printSyntaxDataImplementation(const Record &Node, raw_ostream &OS) {
  auto ClassName = Node.getName();
  auto Kind = stripSyntaxSuffix(ClassName);
  auto SuperclassName = Node.getSuperClasses().back().first->getName();
  auto DataClassName = ClassName + "Data";
  auto DataSuperclassName = SuperclassName + "Data";

  // Constructor
  OS << DataClassName << "::" << DataClassName << "(RC<RawSyntax> Raw, const SyntaxData *Data, const CursorIndex IndexInParent)\n"
  "  : " << DataSuperclassName << "(Raw, Data, IndexInParent) {\n"
  "  assert(Raw->getKind() == SyntaxKind::" << Kind << ");\n"
  "  assert(Raw->Layout.size() == " << getChildrenOf(Node).size() << ");\n";
  for (const auto Child : getChildrenOf(Node)) {
    auto ChildName = Child.getName();
    auto ChildType = getLayoutNodeType(Child);
    auto ChildTypeName = ChildType->getAsString();
    auto ChildVariable = "Raw->getChild(Cursor::" + ChildName + ")";
    if (isToken(ChildType)) {
      printTokenAssertion(ChildVariable.str(), Child, OS);
    } else {
      printSyntaxAssertion(ChildVariable, Child, OS);
    }
  }
  OS << "}\n\n";

  // make
  OS << "RC<" << DataClassName << ">\n" <<
  DataClassName << "::make(RC<RawSyntax> Raw, const SyntaxData *Parent, const CursorIndex IndexInParent) {\n"
  "  return RC<" << DataClassName << "> {\n"
  "    new " << DataClassName << " { Raw, Parent, IndexInParent }\n"
  "  };\n"
  "}\n\n";

  // makeBlank
  OS << "RC<" << DataClassName << ">\n" <<
  DataClassName << "::makeBlank() {\n"
  "  return make(RawSyntax::make(SyntaxKind::" << Kind << ",\n"
  "  {\n";
  for (const auto Child : getChildrenOf(Node)) {
    auto ChildType = getLayoutNodeType(Child);
    if (isToken(ChildType)) {
      auto ChildRec = getLayoutNodeRecord(Child);
      auto TokenKind = ChildRec->getValueAsString("Kind");
      auto TokenSpelling = ChildRec->getValueAsString("Spelling");
      OS << "    TokenSyntax::missingToken(tok::" << TokenKind << ", \"" << TokenSpelling << "\"),\n";
    } else {
      auto ChildKind = getMissingSyntaxKind(Child);
      OS << "    RawSyntax::missing(SyntaxKind::" << ChildKind << "),\n";
    }
  }
  OS << "  },\n"
  "  SourcePresence::Present));\n"
  "}\n\n";

  return false;
}

static bool printSyntaxImplementations(raw_ostream &OS) {
  const auto &Nodes = AllRecords->getDefs();
  for (const auto &Node : Nodes) {
    if (!shouldPrintDef(*Node.second)) {
      continue;
    }
    printAutogenReminder(OS);
    OS << "#pragma mark - " << Node.second->getName() << " API\n\n";
    printSyntaxImplementation(*Node.second, OS);
    OS << "#pragma mark - " << Node.second->getName() << " Data\n\n";
    printSyntaxDataImplementation(*Node.second, OS);
  }

  return false;
}

#pragma mark - SyntaxFactory

static bool printSyntaxFactoryInterface(raw_ostream &OS) {
  HeaderGuard HG { OS };
  Namespaces NS { OS };
  // TODO
  return false;
}


static bool printSyntaxFactoryImplementation(raw_ostream &OS) {
  // TODO
  return false;
}

#pragma mark - SyntaxRewriter

static bool printSyntaxRewriterInterface(raw_ostream &OS) {
  HeaderGuard HG { OS };
  Namespaces NS { OS };
  // TODO
  return false;
}

static bool printSyntaxRewriterImplementation(raw_ostream &OS) {
  // TODO
  return false;
}

static bool genInterface(raw_ostream &OS) {
  switch (getCategory()) {
    case Category::Decl:
    case Category::Expr:
    case Category::Stmt:
    case Category::Type:
    case Category::Pattern:
    case Category::Generic:
    case Category::Attribute:
      return printSyntaxInterfaces(OS);
      break;
    case Category::SyntaxFactory:
      return printSyntaxFactoryInterface(OS);
      break;
    case Category::SyntaxRewriter:
      return printSyntaxRewriterInterface(OS);
      break;
    case Category::Unknown:
      llvm_unreachable("Unknown category given");
  }
}

static bool genImplementation(raw_ostream &OS) {
  printIncludesOfImplementation(OS);

  switch (getCategory()) {
    case Category::Decl:
    case Category::Expr:
    case Category::Stmt:
    case Category::Type:
    case Category::Pattern:
    case Category::Generic:
    case Category::Attribute:
      return printSyntaxImplementations(OS);
    case Category::SyntaxFactory:
      return printSyntaxFactoryImplementation(OS);
    case Category::SyntaxRewriter:
      return printSyntaxRewriterImplementation(OS);
    case Category::Unknown:
      llvm_unreachable("Unknown category given");
  }
}

static bool SyntaxTableGenMain(raw_ostream &OS, RecordKeeper &Records) {
  AllRecords = &Records;
  SyntaxCategories.insert(AllRecords->getClass("Syntax"));
  SyntaxCategories.insert(AllRecords->getClass("Decl"));
  SyntaxCategories.insert(AllRecords->getClass("Stmt"));
  SyntaxCategories.insert(AllRecords->getClass("Expr"));
  SyntaxCategories.insert(AllRecords->getClass("Type"));
  SyntaxCategories.insert(AllRecords->getClass("Pattern"));
  SyntaxCategories.insert(AllRecords->getClass("Token"));
  SyntaxCategories.insert(AllRecords->getClass("SyntaxCollection"));

  switch (options::Action) {
    case ActionType::None:
      llvm::errs() << "action required\n";
      llvm::cl::PrintHelpMessage();
      return true;
    case ActionType::GenInterface:
      return genInterface(OS);
    case ActionType::GenImplementation:
      return genImplementation(OS);
  }
}

int main(int argc, char **argv) {
  sys::PrintStackTraceOnErrorSignal(argv[0]);
  cl::ParseCommandLineOptions(argc, argv);
  if (getCategory() == Category::Unknown) {
    errs() << options::Category << " is an unknown category!\n";
    cl::PrintHelpMessage();
    return 1;
  }
  return TableGenMain(argv[0], &SyntaxTableGenMain);
}
